development:
  sessions:
    default:
      database: blogpian-rails-dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: blogpian-rails-test
      hosts:
        - localhost:27017